### ISSUE TITLE
Rerun generate_librimix.sh error

### ISSUE THREAD

**Issue by sTarAnna** [JorisCos/LibriMix#10]
The first time I run the generate_librimix.sh, it downloads all data and generates the data i need. But if i rerun the .sh to generate Libri2/3Mix or some subsets of it, an error occurs.

```

bash ./generate_librimix.sh ./data/

Augmenting ./data//wham_noise/tr files
Change speed with factor 0.8
  0%|                                                 | 0/60000 [00:00<?, ?it/s]
concurrent.futures.process._RemoteTraceback: 
"""

Traceback (most recent call last):
  File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "scripts/augment_train_noise.py", line 42, in apply_fx
    s = s[:, 0]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
"""
The above exception was the direct cause of the following exception:
  Traceback (most recent call last):
  File "scripts/augment_train_noise.py", line 52, in <module>
    main(args)
  File "scripts/augment_train_noise.py", line 24, in main
    augment_noise(sound_paths, 0.8)
  File "scripts/augment_train_noise.py", line 33, in augment_noise
    chunksize=10
  File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/site-packages/tqdm/contrib/concurrent.py", line 127, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/site-packages/tqdm/contrib/concurrent.py", line 73, in _executor_map
    ex.map(fn, *iterables, **map_args), **kwargs))

  File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()  
File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/aiz/Program/anaconda3/envs/ss/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by JorisCos** [comment]
If you want to rerun the script you have to comment out the augmentation part.

**Comment by mpariente** [comment]
Maybe we could add a check about that, it would be more user-friendly

**Comment by JorisCos** [comment]
Yes for sure, it's been a problem since the start. I will look into it

**Comment by Yancongs** [comment]
> If you want to rerun the script you have to comment out the augmentation part.

where is the augmentation part?

**Comment by JorisCos** [comment]
This line `python scripts/augment_train_noise.py --wham_dir $wham_dir` in `generate_librimix.sh`.
