### ISSUE TITLE
Generating 4 and 5 source mixtures

### ISSUE THREAD

**Issue by th3geek** [JorisCos/LibriMix#15]
Hi,

I'm trying to generate 4 and 5 source mixtures for training Facebook research's svoice but looking at the script I don't see the location where the `n_src` variable is set. I tried changing `for n_src in 2 3; do` to `for n_src in 2 3 4 5; do` which generates the 2 and 3 mixtures just fine but get an error that the metadata files hadn't been generated for libri4mix. Any suggestions on how I'd go about getting the script to do 4 and 5 source mixtures?

Thank you.

**Comment by mpariente** [comment]
I think it's there: https://github.com/JorisCos/LibriMix/blob/master/scripts/create_librimix_metadata.py#L38

So: 
-Generate the metadata with 4 and 5 sources
- Run the generation from the metadata files. 

Is that working?

**Comment by th3geek** [comment]
So if I try to run `create_librispeech_metadata.py` directly I'm getting the following errors:

```
(librimix) user@system:/media/user/svoice/LibriMix$ python scripts/create_librimix_from_metadata.py --librispeech_dir librimix/     --wham_dir librimix/wham_noise/     --metadata_dir metadata/LibriSpeech/     --librimix_outdir librimix-2nd-try/     --n_src 4     --freqs 16k     --modes min max     --types mix_clean mix_both mix_single
Creating mixtures and sources from metadata/LibriSpeech/dev-clean.csv in librimix-2nd-try/Libri4Mix/wav16k/min/dev
  0%|                                                                                                            | 0/2303 [00:00<?, ?it/s]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'mixture_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/media/user/svoice/LibriMix/scripts/create_librimix_from_metadata.py", line 158, in process_utterance
    mix_id, gain_list, sources = read_sources(row, n_src, librispeech_dir,
  File "/media/user/svoice/LibriMix/scripts/create_librimix_from_metadata.py", line 233, in read_sources
    mixture_id = row['mixture_ID']
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/site-packages/pandas/core/series.py", line 853, in __getitem__
    return self._get_value(key)
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/site-packages/pandas/core/series.py", line 961, in _get_value
    loc = self.index.get_loc(label)
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'mixture_ID'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/user/svoice/LibriMix/scripts/create_librimix_from_metadata.py", line 415, in <module>
    main(args)
  File "/media/user/svoice/LibriMix/scripts/create_librimix_from_metadata.py", line 58, in main
    create_librimix(librispeech_dir, wham_dir, librimix_outdir, metadata_dir,
  File "/media/user/svoice/LibriMix/scripts/create_librimix_from_metadata.py", line 71, in create_librimix
    process_metadata_file(csv_path, freqs, n_src, librispeech_dir,
  File "/media/user/svoice/LibriMix/scripts/create_librimix_from_metadata.py", line 114, in process_metadata_file
    process_utterances(md_file, librispeech_dir, wham_dir, freq, mode,
  File "/media/user/svoice/LibriMix/scripts/create_librimix_from_metadata.py", line 133, in process_utterances
    for results in tqdm.contrib.concurrent.process_map(
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 130, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/home/user/anaconda3/envs/librimix/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
KeyError: 'mixture_ID'
```

**Comment by mpariente** [comment]
Did you generate the metadata from Librispeech itself?

**Comment by th3geek** [comment]
Opps, I was running the wrong script and had an incorrect directory to boot. The metadata creation script is running right now for 4 mixtures. fingers crossed, it'll finish. I'll update. Thanks for your fast response.

**Comment by th3geek** [comment]
I was able to get it to work properly by using the metadata creation script. It would be a nice feature if it were possible to specify the number of sources as an argument to the main `generate_librimix.sh` script. 

Thanks for your help
