### ISSUE TITLE
gitbash run generate_librimix.sh on windows

### ISSUE THREAD

**Issue by scarlet1832** [JorisCos/LibriMix#16]
$ sh generate_librimix.sh
  0%|          | 0/20000 [00:00<?, ?it/s]
Augmenting E:/librimixdataset/LibriMix-master/librimixdataset/wham_noise\tr files
Change speed with factor 0.8
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Anaconda3\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Anaconda3\lib\concurrent\futures\process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "C:\Anaconda3\lib\concurrent\futures\process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "E:\librimixdataset\LibriMix-master\scripts\augment_train_noise.py", line 60, in apply_fx
    s = fx(s)
  File "C:\Anaconda3\lib\site-packages\pysndfx\dsp.py", line 413, in __call__
    stdout, stderr = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE).communicate(stdin.tobytes(order="F"))
  File "C:\Anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/augment_train_noise.py", line 68, in <module>
    main(args)
  File "scripts/augment_train_noise.py", line 40, in main
    augment_noise(sound_paths, 0.8)
  File "scripts/augment_train_noise.py", line 49, in augment_noise
    chunksize=10
  File "C:\Anaconda3\lib\site-packages\tqdm\contrib\concurrent.py", line 130, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\Anaconda3\lib\site-packages\tqdm\contrib\concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "C:\Anaconda3\lib\site-packages\tqdm\std.py", line 1166, in __iter__
    for obj in iterable:
  File "C:\Anaconda3\lib\concurrent\futures\process.py", line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: [WinError 2] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒

I dont know what to do with it.

**Comment by grdore** [comment]
I think this is because you haven't installed sox. It's not listed in the requirements.txt doc but is listed in the readme.md file.

conda install -c groakat sox

Hope that helps - took me a day of head scratching to find it.
