### ISSUE TITLE
wham_noise file not found error

### ISSUE THREAD

**Issue by Abhishek577** [JorisCos/LibriMix#34]
raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '2/wham_noise/cv/01nc0201_1.2143_02ec0215_-1.2143.wav': System error.

Download wham_noise into 2
--2024-09-13 09:38:13--  https://storage.googleapis.com/whisper-public/wham_noise.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.182.187, 142.250.192.187, 142.250.206.123, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.182.187|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-09-13 09:38:14 ERROR 404: Not Found.

Creating libri7mix_dev-clean.csv file in ./metadata/Libri7Mix
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py:269: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  samples = random.sample(index, min(len(index), 10 * n_src))  # Heuristic - draw 10*n_src samples, in order to hopefully find n_src unique speakers.
Generating pairs
Removing duplicates
  0%|                                                                                                                    | 0/3000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py", line 495, in <module>
    main(args)
  File "/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py", line 63, in main
    create_librimix_metadata(librispeech_dir, librispeech_md_dir, wham_dir,
  File "/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py", line 116, in create_librimix_metadata
    create_librimix_metadata_single_set(librispeech_dir, librispeech_md_dir, wham_dir, wham_md_dir, md_dir, n_src,
  File "/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py", line 142, in create_librimix_metadata_single_set
    mixtures_md, mixtures_info = create_librimix_df(
  File "/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py", line 199, in create_librimix_df
    sources_info, sources_list_max = add_noise(
  File "/home/wesee/Desktop/ABHISHEK/projects/svoice_ghani/LibriMix/scripts/create_librimix_metadata.py", line 383, in add_noise
    n, _ = sf.read(noise_path, dtype='float32')
  File "/home/wesee/.local/lib/python3.10/site-packages/soundfile.py", line 285, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "/home/wesee/.local/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/wesee/.local/lib/python3.10/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '2/wham_noise/cv/01nc0201_1.2143_02ec0215_-1.2143.wav': System error.

how to resolve this error

**Comment by Abhishek577** [comment]
add the custom url in download_librispeech_and_wham.sh 
https://my-bucket-a8b4b49c25c811ee9a7e8bba05fa24c7.s3.amazonaws.com/wham_noise.zip
